### ISSUE TITLE
Potential to improve documentation

### ISSUE THREAD

**Issue by Metalyph** [jgravois/esri-leaflet-gp#36]
So I'm coming from [this thread](https://geonet.esri.com/thread/181115) requesting that I posted some areas of the documentation that were causing me some confusion.

While I was searching through the documentation I noticed that [this page](https://esri.github.io/esri-leaflet/api-reference/services/gp-service.html) doesn't list the setParam() or setOutputParam() methods[?]. 

On the same vein as the parameter fields, I think it would be helpful to link to [this page](http://resources.arcgis.com/en/help/main/10.1/index.html#/Task_parameter_properties_REST/005700000070000000/) or perhaps have your own version of that page, as I understand there are some extra steps.

My other problem was figuring out how to accomplish the geoprocessing task that I wanted.  I found [this example](https://esri.github.io/esri-leaflet/examples/gp-plugin.html), which is certainly helpful, but translating that to other geoprocessing tasks can be challenging.  However, (as far as I understand so far) there seem to be a limitless number of task / parameter combinations, so creating documentation for these tasks might be an overly large undertaking.

Hopefully this is helpful, please let me know if you have any follow up questions or would like me to clarify anything.

**Comment by jgravois** [comment]
thanks for this @Metalyph.

> I noticed that [this page](https://esri.github.io/esri-leaflet/api-reference/services/gp-service.html) doesn't list the setParam() or setOutputParam() methods[?].

its a bit idiosyncratic, but `L.esri.GP.Service` is a wrapper object that is instantiated and used only to call `createTask()`.  the reason i wrote the plugin this way initially is because it exposed a mechanism thats already built into esri-leaflet [core](https://esri.github.io/esri-leaflet/api-reference/services/service.html) to do optional things like handle authentication or acknowledge that a particular server doesn't support CORS.

>  (as far as I understand) there seem to be a limitless number of task / parameter combinations

This is absolutely true.  This plugin fetches metadata from the service and is able to determine its input parameter names and valid input types, but i've never been able to think of any shortcuts to assist developers in setting appropriate values and associating them with parameters that are guaranteed to have a unique name.

### opportunities for improvement
- [ ] consider letting folks instantiate a `GP.Task` directly and hydrate an internal `_service` for them
- [x] [`GPLinearUnit`](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/GP_Result/02r3000000q7000000/) JSON literals should be recognized without being coerced to a `string`
- [ ] when the plugin fetches metadata, it should call `setOutputParam()` internally.
- [ ] write more live samples
- [ ] what else?

**Comment by jgravois** [comment]
i know its been ages, but...

- [X] [`GPLinearUnit`](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/GP_Result/02r3000000q7000000/) JSON literals should be recognized without being coerced to a `string`
